### ISSUE TITLE
download link is broken

### ISSUE THREAD

**Issue by julienlau** [Siteminds/graylog-plugin-alertmanager#1] opened 2018-10-10 15:57 UTC
Hi,
I would like to test this plugin, but download link is broken.

**Comment by thsaravana** [comment] 2019-03-28 02:52
@julienlau Please use https://github.com/Siteminds/graylog-plugin-alertmanager/releases until the issue is fixed (PR gets merged).

**Closed as completed** 2019-03-28 06:27 UTC
